simplified implementation for the sanity check by learning that bash shell on windows is 'git bash for windows' which means that it still uses the windows node runtime but bash shell so the implementation can stay the same between OSes now.  a performance update was that we can do npm prune to get rid of dev dependencies instead of doing an npm ci which will cause a full reinstall.  use printf in both branches for consistency's sake and make it pipe to stderr instead of stdout.  instead of doing a subshell for the first printf, make it run in the same shell instead which is just a minor improvement.  fixed a bug where the backticks in double quotes on the second printf would cause it to run 'saf -v' while we just wanted the raw text - changing printf to use single quotes fixed this.
Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

diff --git a/.github/workflows/e2e-ci.yml b/.github/workflows/e2e-ci.yml
--- a/.github/workflows/e2e-ci.yml
+++ b/.github/workflows/e2e-ci.yml
@@ -43,40 +43,18 @@ jobs:
         run: |
           curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-auditor
 
-      - name: Install dependencies, compile, and run tests on ${{ matrix.platform }}
+      - name: Run E2E tests on ${{ matrix.platform }}
         run: |
           npm run prepack
           npm run test:ci
 
-      - name: Sanity check that the SAF CLI works with no dev dependencies on windows
-        if: ${{ matrix.platform == 'windows' }}
-        shell: pwsh
+      - name: Smoke test to see if the CLI works with just production dependencies
+        shell: bash
         run: |
-          npm ci --omit=dev
-          npm run prepack
-          $stderrFile = New-TemporaryFile
-          ./bin/run -v 2> $stderrFile.FullName 1> $null
-          $exitCode = $LASTEXITCODE
-          $stderr = Get-Content $stderrFile.FullName -Raw
-          Remove-Item $stderrFile
-          if ($exitCode -eq 0) {
-            if (($null -ne $stderr) -and ($stderr.Trim())) {
-              Write-Host "Failed: received the following stderr:`n$stderr"
-              exit 1
-            }
-          } else {
-            Write-Host "Failed: received a non-zero exit code when doing 'saf -v'"
-            exit 1
-          }
-
-      - name: Sanity check that the SAF CLI works with no dev dependencies on ubuntu or macos
-        if: ${{ matrix.platform == 'ubuntu' || matrix.platform == 'macos' }}
-        run: |
-          npm ci --omit=dev
-          npm run prepack
+          npm prune --omit=dev --ignore-scripts --no-audit --no-fund
           if stderr=$(./bin/run -v 2>&1 1>/dev/null); then
-            [ -z "$stderr" ] || (printf "Failed: received the following stderr:\n%s\n" "$stderr"; exit 1)
+            [ -z "$stderr" ] || { printf 'Failed: received the following stderr:\n%s\n' "$stderr" >&2; exit 1; }
           else
-            echo "Failed: received a non-zero exit code when doing `saf -v`"
+            printf 'Failed: received a non-zero exit code when doing `saf -v`\n%s\n' "$stderr" >&2
             exit 1
           fi
