Ironbank workflow improvements (#5004)
* add github.sha as a docker tag

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

* iron bank workflow improvement to handle networking/processing delays from dockerhub

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

---------

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

diff --git a/.github/workflows/push-to-docker-main.yml b/.github/workflows/push-to-docker-main.yml
--- a/.github/workflows/push-to-docker-main.yml
+++ b/.github/workflows/push-to-docker-main.yml
@@ -29,12 +29,33 @@ jobs:
           context: .
           push: true
           platforms: "linux/amd64,linux/arm64"
-          tags: mitre/saf:latest
+          tags: mitre/saf:latest,mitre/saf:${{ github.sha }}
       - name: Get Docker SHA since the Iron Bank release requires us to specify the exact resources we need them to pull into the environment
         shell: bash
         id: get-docker-sha
         run: |
-          echo "DOCKER_SHA=$(docker pull mitre/saf:latest > /dev/null 2>&1 && docker inspect --format='{{index .RepoDigests 0}}' mitre/saf:latest | cut -d '@' -f 2)" >> $GITHUB_ENV
+          MAX_RETRIES=5
+          RETRY_DELAY=0.5 # in seconds
+          RETRY_COUNT=0
+          SUCCESS=false
+
+          while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
+            if docker pull mitre/saf:${{ github.sha }}; then
+              SUCCESS=true
+              break
+            else
+              RETRY_COUNT="$((RETRY_COUNT + 1))"
+              echo "Retry $RETRY_COUNT/$MAX_RETRIES: Docker pull failed.  Retrying in $RETRY_DELAY seconds..."
+              sleep "$RETRY_DELAY"
+            fi
+          done
+
+          if [ "$SUCCESS" = true ]; then
+            echo "DOCKER_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' mitre/saf:${{ github.sha }} | cut -d '@' -f 2)" >> $GITHUB_ENV
+          else
+            echo "Docker pull failed after $MAX_RETRIES attempts."
+            exit 1
+          fi
       - name: Upgrade Iron Bank
         uses: mitre/ironbank_release_action@v1
         with:
